# GitHub Actions Workflow created for handling the release process based on the draft release prepared with the Build workflow.

name: Release
on:
  release:
    types: [prereleased, released]

jobs:
  release:
    runs-on: windows-latest
    name: Publish the extension to Visual Studio Marketplace
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Donwload extension from latest release assets
        uses: robinraju/release-downloader@v1.9
        with: 
          latest: true
          fileName: conan-vs-extension.vsix
          out-file-path: conan-vs-extension.vsix
          extract: false
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Visual Studio Marketplace Publisher
        uses: CalvinAllen/action-vs-marketplace-publish@v1
        with:
          marketplace-pat: ${{ secrets.vs_marketplace_pat }}  # Personal Access Token to upload to the VS Marketplace
          publish-manifest-path: vsixManifest.json
          vsix-path: conan-vs-extension.vsix
